require:
  # - rubocop-jekyll
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - binstub/**/*
    - demo/_site/*
    - vendor/**/*
    - Gemfile*
  NewCops: enable

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 55

Metrics/BlockLength:
  Exclude:
    - jekyll_plugin_support.gemspec
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 25

Naming/FileName:
  Exclude:
    - Rakefile
    - "*.md"

RSpec/ExampleLength:
  Max: 30

RSpec/SpecFilePathFormat:
  Enabled: false
  IgnoreMethods: true

RSpec/SpecFilePathSuffix:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 15

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
