#require: rubocop-jekyll
#inherit_gem:
#  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
  NewCops: enable
  TargetRubyVersion: 2.6

# Gemspec/RequireMFA:
#   Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
