#!/bin/bash

# shellcheck disable=SC2086,SC2155,SC2059

function help {
  echo "
$(basename $0) - Run the demo Jekyll website.
By default the demo Jekyll website runs without restriction under ruby-debug-ide and debase,
and listens on 0.0.0.0:1234.
Options:
  -h  Show this error message
  -r  Run freely, without a debugger
"
  exit 1
}


unset RUN_FREE
while getopts "hr" OPT; do
  case "$OPT" in
    h) help ;;

    r) export RUN_FREE=true
       echo "The RUN_FREE option was specified (without a debugger)."
       ;;

    *) help ;;
  esac
done
shift $((OPTIND-1))


# dispatcher-port and dispatcher-port are arbitrarily chosen to prevent conflicts with other instances.

run="serve \
    --livereload_port 25721 \
    --force_polling \
    --host 0.0.0.0 \
    --port 4444 \
    --future \
    --incremental \
    --livereload \
    --drafts \
    --unpublished"

GIT_ROOT="$( git rev-parse --show-toplevel )"
cd "${GIT_ROOT}/demo" || exit

bundle install
bundle update

bundle exec jekyll clean # Ensure all hooks get called

if [ "$RUN_FREE" ]; then
  bundle exec ../exe/jekyll $run
else
  bundle exec rdebug-ide \
    --host 0.0.0.0 \
    --port 1234 \
    --dispatcher-port 26162 \
    -- ../exe/jekyll $run
fi
