#!/bin/bash

function help {
  echo "
$(basename $0) - Run the demo Jekyll website.
By default the demo Jekyll website runs without restriction under debug,
and listens on 0.0.0.0.
Options:
  -h  Show this error message
  -r  Run freely, without a debugger
"
  exit 1
}

unset RUN_FREE
while getopts "hr" OPT; do
  case "$OPT" in
    h) help ;;

    r) export RUN_FREE=true
       echo "The RUN_FREE option was specified (without a debugger)."
       ;;

    *) help ;;
  esac
done
shift $((OPTIND-1))

# Change to parent directory of this script
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
cd "$DIR/.." || exit

run="serve \
    --livereload_port 25721 \
    --force_polling \
    --host 0.0.0.0 \
    --port 4444 \
    --future \
    --incremental \
    --livereload \
    --drafts \
    --unpublished"

GIT_ROOT="$( git rev-parse --show-toplevel )"
cd "${GIT_ROOT}/demo" || exit

export BUNDLE_WITH=development
rm -f Gemfile.lock
bundle
bundle exec jekyll clean # Ensure all hooks get called

if [ "$RUN_FREE" ]; then
  bundle exec jekyll $run
else
  bundle exec rdbg -O --port=0 -- ../binstub/jekyll $run
fi
