source 'https://rubygems.org'

gem 'ffi'
gem 'jekyll', '~> 4.3.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'
gem 'sprockets'
gem 'webrick'

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll_href', path: "../"
  gem "jekyll_plugin_logger"
  # gem 'jekyll-sort'
  gem 'jekyll-tagging'
  # gem 'kramdown'
end

gem 'debase', "0.2.5.beta2", require: false
gem 'debase-ruby_core_source', '~> 0.10.15', require: false
# gem "rake", "~> 13.0", require: false
# gem 'rspec', require: false
gem 'rubocop', '= 1.18.0', require: false
gem 'ruby-debug-ide', require: false
