source 'https://rubygems.org'

gem 'ffi'
gem 'ptools'

jekyll_plugin_support = ENV.fetch('jekyll_plugin_support', nil)

group :jekyll_plugins do
  gem 'jekyll-assets', git: 'https://github.com/envygeeks/jekyll-assets'
  gem 'jekyll_draft'
  gem 'jekyll-environment-variables'
  gem 'jekyll_href', path: '../'
  gem 'jekyll_plugin_support', path: jekyll_plugin_support
  gem 'jekyll-tagging'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
